### ISSUE TITLE
Support for Public Use?

### ISSUE THREAD

**Issue by m-s-morgan** [spoonconsulting/cordova-plugin-background-upload#136]
Hi guys, just wondering if you stopped supporting this plugin for public use. Unless there's a strange issue on my end, it doesn't seem like any releases have been published to NPM since v1.1.0 and the addition of this in the plugin.xml makes it not so friendly for use.
```
<edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application">
    <application android:name="com.orm.SugarApp" />
</edit-config>
```
It's no big deal if that was the decision made, I just wanted to confirm with you all what your plans were for this plugin since I've been a fan for awhile now. Appreciate it!

**Comment by ombr** [comment]
Hi @m-s-morgan,

We are still supporting this plugin, but realized we were doing it wrong in the previous version:

The plugin is getting notifications from the os while the webview is off, so we have to save the notification in a database to replay them later to the webview.

We decided to use http://satyan.github.io/sugar/index.html as the ORM to do this quickly.
I understand the way SugarORM needs to be setup is not great for a cordova plugin.

If you want, you are more than welcome to submit a pull-request and drop SugarApp, but two thing you have to keep in mind, we need to be backward compatible and we need to be able to have migration on thoses tables.

Thanks.

Luc

**Comment by m-s-morgan** [comment]
Thanks Luc, appreciate the explanation.

**Comment by hodlonaut** [comment]
@m-s-morgan @ombr so what is the recommended way of dealing with the 'Failed to install '<plugin name>': Error: <plugin name> cannot be added. <edit-config> changes in this plugin conflicts with <edit-config> changes in config.xml. Conflicts must be resolved before plugin can be added. when trying to use latest versions of this? If I remove the edit-config in the plugin my parent application builds but then (rather expectedly) barfs at run-time with "SugarContext has not been initialized properly. Call SugarContext.init(Context) in your Application.onCreate() method and SugarContext.terminate() in your Application.onTerminate() method."

**Comment by azharbeebeejaun** [comment]
@hodlonaut take a look at how it was done in tag [2.0.3](https://github.com/spoonconsulting/cordova-plugin-background-upload/releases/tag/2.0.3).
[plugin.xml](https://github.com/spoonconsulting/cordova-plugin-background-upload/blob/8cf5f6b9893bf4b57c6bb3e431cf931bb5fab25b/plugin.xml)
[Application.java](https://github.com/spoonconsulting/cordova-plugin-background-upload/blob/8cf5f6b9893bf4b57c6bb3e431cf931bb5fab25b/src/android/Application.java)

Similarly, if you don't want edit-config in the plugin, you would have to extend `com.spoon.backgroundfileupload.Application` in your Application.java class (or the starting point of your app). This is so that the ORM and the uploader are properly initialized.
