### ISSUE TITLE
Is it possible to use this plugin with Phonegap BUILD?

### ISSUE THREAD

**Issue by DanLuczywo** [spoonconsulting/cordova-plugin-background-upload#2]
Is it possible to use this plugin with Phonegap BUILD?

Thanks

**Comment by mevinDhun** [comment]
Yes, it has been tested successfully on android via Phonegap build.

**Comment by DanLuczywo** [comment]
Thanks for the fast response. What about iOS ?

**Comment by mevinDhun** [comment]
Since the ios part of this plugin relies on the [swift-support plugin](https://github.com/akofman/cordova-plugin-add-swift-support) which uses hooks, it will not compile on phonegap build. Only when PGB allows running of cordova hooks, then this plugin will work. [Adobe clearly mentioned it has no intention of allowing hooks to run on the build service](https://forums.adobe.com/message/9318835#9318835).

**Comment by mevinDhun** [comment]
Hi @DanLuczywo the latest version of this plugin has been re-written on objective C and should now work on Phonegap Build.
