### ISSUE TITLE
How to modify FileUploader.m to use basic PUT request (not multipart)

### ISSUE THREAD

**Issue by maxcodefaster** [spoonconsulting/cordova-plugin-background-upload#219]
Like others, I also have the use case of PUTting a file directly into S3 storage. I have successfully changed the UploadTask.java file to use a simple PUT request: https://github.com/maxcodefaster/cordova-plugin-background-upload/blob/master/src/android/UploadTask.java#L342

Can you please help me to modify the FileHelper.m to do the same for iOS? I tried, but i am not familiar with Objective-C.

**Comment by zafirskthelifehacker** [comment]
Hello @maxcodefaster,

https://github.com/spoonconsulting/cordova-plugin-background-upload/blob/dfa0f4267b9a08b849c64b4ad0b76c1fd0191b39/src/ios/FileUploader.m#L131

`[serializer multipartFormRequestWithMethod:@"POST"`

You can change this line to `PUT` rather than `POST`

As not multipart requests, use `requestWithMethod` rather than `multipartFormRequestWithMethod`

Regards,
Zafir

**Comment by maxcodefaster** [comment]
Made a Fork here: https://www.npmjs.com/package/cordova-plugin-background-upload-put-s3
