### ISSUE TITLE
Add the ability to set the HTTP Method of the request (PUT, PATCH) and etc...

### ISSUE THREAD

**Issue by omardoma** [spoonconsulting/cordova-plugin-background-upload#62]
Great work on the plugin, works perfectly and saved my team a lot of time and effort to implement what we needed!

One thing though that I can't seem to find is the ability to set the HTTP request's method as not all of my uploads are POST. It will be great if it can be added in the next version.

**Comment by mevinDhun** [comment]
Hi @omardoma, thanks for using the plugin. We currently do not have any plans on adding this feature but pull requests are most welcome.

**Comment by omardoma** [comment]
@mevinDhun Thank YOU for creating the plugin! if thats the case then I will try to add it and create a pull request whenever I have the time, maybe in the coming weekend.

**Comment by CyberCyclone** [comment]
For those that have found that this plugin doesn't work with AWS S3, it's because of this issues. I.e, the plugin using POST when S3 needs PUT.

**Comment by albertleao** [comment]
@CyberCyclone Is this a recent issue? I used to be able to upload to s3 just fine but recently it stopped working.

**Comment by CyberCyclone** [comment]
@albertleao I don't see how it could have worked before. As far as I know, S3 doesn't have a handler / runner that would be able to process form types. As in, this plugin deliberately adds form headers and footer data of which a HTTP server would typically removed. Since S3 simply dumps whatever it's been given. So while you can definitely upload, it will appear corrupt.

Since there isn't any plans to change this, you'll have to change the code so it sends as PUT. From memory, I had more issues with iOS than Android.

**Comment by albertleao** [comment]
@CyberCyclone Just tested it and it's working fine in iOS with direct upload to s3.

**Comment by ombr** [comment]
Hi @albertleao  we are currently working on a new version of the plugin. You should check this version: https://github.com/spoonconsulting/cordova-plugin-background-upload/pull/84
We are direct uploading on s3 without any issue.

**Comment by maxcodefaster** [comment]
Made a Fork here: https://www.npmjs.com/package/cordova-plugin-background-upload-put-s3
